<a href="https://colab.research.google.com/github/imb96/ML/blob/main/ML_week_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **실습 1 - pandas 기본문법**

In [ ]:
import pandas as pd

In [ ]:
df = pd.DataFrame(
    {
        "Name": [
            "Braund, Mr . Owen Harris",
            "Allen, Mr. William Henry",
            "Bonnell, Miss Elizabeth",
        ],
        "Age": [22, 35, 58],
        "Sex": ["male", "male", "female"]
    }
)

In [ ]:
df

Name  Age     Sex
0  Braund, Mr . Owen Harris   22    male
1  Allen, Mr. William Henry   35    male
2   Bonnell, Miss Elizabeth   58  female

In [ ]:
df["Age"]

0    22
1    35
2    58
Name: Age, dtype: int64

In [ ]:
ages = pd.Series([20, 30, 40], name="Age")

In [ ]:
ages

0    20
1    30
2    40
Name: Age, dtype: int64

In [ ]:
df["Age"].max()

58

In [ ]:
ages.max()

40

# 실습 1- numpy 기본문법

In [12]:
import numpy as np

In [13]:
#1차원
a = np.array([1,2,3,4,5,6])

In [14]:
a

array([1, 2, 3, 4, 5, 6])

In [15]:
#2차원
data = np.array([[1,2], [3,4], [5,6]])

In [16]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [17]:
data[0,1]

np.int64(2)

In [21]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [22]:
data[0:2, 0]

array([1, 3])

In [23]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
array_example = np.array([[[0,1,2,3],[4,5,6,7]], [[0,1,2,3],[4,5,6,7]], [[0,1,2,3],[4,5,6,7]]])

In [27]:
# 차원
array_example.ndim

3

In [28]:
# 크기
array_example.size

24

In [29]:
# 모양
array_example.shape

(3, 2, 4)

In [31]:
data = np.array([1,2,3,4,5,6])
data

array([1, 2, 3, 4, 5, 6])

In [32]:
# 2차원으로 변환
data.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
# 2차원으로 변환
data.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [35]:
# 더하기
data = np.array([[1,2], [3,4], [5,6]])
ones_row = np.array([1,1])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [36]:
# 전체 array에서 최대값
data.max()

np.int64(6)

In [37]:
data.min()

np.int64(1)

In [38]:
data.sum()

np.int64(21)

# 실습 2 -파일 데이터 읽기/쓰기

In [39]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [40]:
csv_arr = np.array([[1,2,3,4], [5,6,7,8]])

In [42]:
np.savetxt('/content/drive/MyDrive/Colab Notebooks/data/new_file.csv', csv_arr)

In [43]:
np.loadtxt('/content/drive/MyDrive/Colab Notebooks/data/new_file.csv')

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])